export const USER_LIST = [
    {
        uid: '1',
        email: 'achilal@techprovint.com',
        displayName: 'Achila Liyanarachchi',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'chaminm@techprovint.com',
        displayName: 'Chamin Maldeniya',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'erangak@techprovint.com',
        displayName: 'Eranga Kariyawasam',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'harshanad@techprovint.com',
        displayName: 'Harshana Dissanayaka',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'methmalg@techlabs.tech',
        displayName: 'Methmal Godage',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'nalinaw@techlabs.tech',
        displayName: 'Nalina Wijesundara',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'piriyangac@techprovint.com',
        displayName: 'Piriyanga Christopher',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'pradeeps@techprovint.com',
        displayName: 'Pradeep Sanjaya',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'ravindug@techprovint.com',
        displayName: 'Ravindu Gayal',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'sahasp@techprovint.com',
        displayName: 'Sahas Punchihewa',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'sandarekhar@techprovint.com',
        displayName: 'Sandarekha Ramanayake',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'sandeeshr@techprovint.com',
        displayName: 'Sandeesh Rajagopal',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'sanjeewan@techprovint.com',
        displayName: 'Sanjeewa Nayanananda',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'seneshs@techlabs.tech',
        displayName: 'Senesh Sirimanne',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'surenid@techprovint.com',
        displayName: 'Sureni Dhanasekara',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'susanthap@techprovint.com',
        displayName: 'Susantha Pathirana',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'tharangap@techlabs.tech',
        displayName: 'Tharanga Premathilake',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'thushanr@techprovint.com',
        displayName: 'Thushan Ranasinghe',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'venurar@techlabs.tech',
        displayName: 'Venura Rajapaksha',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'virajs@techprovint.com',
        displayName: 'Viraj Sameera',
        photoURL: 'photo',
    },
    {
        uid: '1',
        email: 'bhavanl@techprovint.com',
        displayName: 'Bhavaneetharan Loganathan',
        photoURL: 'photo',
    },
];
