export const USER_LIST = [
    {
        uid: '1',
        email: 'achilal@techprovint.com',
        displayName: 'Achila Liyanarachchi',
        photoURL: 'photo',
    },
    {
        uid: '2',
        email: 'chaminm@techprovint.com',
        displayName: 'Chamin Maldeniya',
        photoURL: 'photo',
    },
    {
        uid: '3',
        email: 'erangak@techprovint.com',
        displayName: 'Eranga Kariyawasam',
        photoURL: 'photo',
    },
    {
        uid: '4',
        email: 'harshanad@techprovint.com',
        displayName: 'Harshana Dissanayaka',
        photoURL: 'photo',
    },
    {
        uid: '5',
        email: 'methmalg@techlabs.tech',
        displayName: 'Methmal Godage',
        photoURL: 'photo',
    },
    {
        uid: '8',
        email: 'pradeeps@techprovint.com',
        displayName: 'Pradeep Sanjaya',
        photoURL: 'photo',
    },
    {
        uid: '9',
        email: 'ravindug@techprovint.com',
        displayName: 'Ravindu Gayal',
        photoURL: 'photo',
    },
    {
        uid: '10',
        email: 'sahasp@techprovint.com',
        displayName: 'Sahas Punchihewa',
        photoURL: 'photo',
    },
    {
        uid: '12',
        email: 'sandeeshr@techprovint.com',
        displayName: 'Sandeesh Rajagopal',
        photoURL: 'photo',
    },
    {
        uid: '14',
        email: 'seneshs@techlabs.tech',
        displayName: 'Senesh Sirimanne',
        photoURL: 'photo',
    },
    {
        uid: '15',
        email: 'surenid@techprovint.com',
        displayName: 'Sureni Dhanasekara',
        photoURL: 'photo',
    },
    {
        uid: '16',
        email: 'susanthap@techprovint.com',
        displayName: 'Susantha Pathirana',
        photoURL: 'photo',
    },
    {
        uid: '19',
        email: 'venurar@techlabs.tech',
        displayName: 'Venura Rajapaksha',
        photoURL: 'photo',
    },
    {
        uid: '20',
        email: 'virajs@techprovint.com',
        displayName: 'Viraj Sameera',
        photoURL: 'photo',
    },
    {
        uid: '21',
        email: 'bhavanl@techprovint.com',
        displayName: 'Bhavaneetharan Loganathan',
        photoURL: 'photo',
    },
];
